<?php

return [
    [
        'key'  => 'sales.payment_methods.raiaccept',
        'name' => 'RaiAccept',
        'info' => 'RaiAccept payment gateway configuration',
        'sort' => 5,

        'fields' => [
            [
                'name'          => 'title',
                'title'         => 'Title',
                'type'          => 'text',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => true,
            ],
            [
                'name'          => 'description',
                'title'         => 'Description',
                'type'          => 'textarea',
                'channel_based' => true,
                'locale_based'  => true,
            ],
            [
                'name'          => 'image',
                'title'         => 'Logo',
                'type'          => 'image',
                'info'          => 'Upload payment method logo',
                'channel_based' => false,
                'locale_based'  => false,
                'validation'    => 'mimes:bmp,jpeg,jpg,png,webp',
            ],
            [
                'name'          => 'merchant_id',
                'title'         => 'Merchant ID',
                'type'          => 'text',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'terminal_id',
                'title'         => 'Terminal ID',
                'type'          => 'text',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'gateway_url',
                'title'         => 'Gateway URL',
                'type'          => 'text',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1|url',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 'https://ecg.test.upc.ua/rbko/pay',
            ],
            [
                'name'          => 'currency_numeric',
                'title'         => 'Numeric Currency Code',
                'type'          => 'text',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => '978',
            ],
            [
                'name'          => 'version',
                'title'         => 'Gateway Version',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => '1.0',
            ],
            [
                'name'          => 'locale',
                'title'         => 'Gateway Locale',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 'sq',
            ],
            [
                'name'          => 'private_key_pem',
                'title'         => 'Merchant Private Key PEM',
                'type'          => 'textarea',
                'info'          => 'Paste full private key content including BEGIN/END lines',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'bank_public_key_pem',
                'title'         => 'Bank Public Key / Certificate PEM',
                'type'          => 'textarea',
                'info'          => 'Paste full bank certificate/public key for response verification',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'debug',
                'title'         => 'Debug Mode',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'active',
                'title'         => 'Enable',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'    => 'sort',
                'title'   => 'Sort Order',
                'type'    => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                ],
            ],
        ],
    ],
];
